version: '3'

### IMPORTANT NOTE: only import via inline definition. 
# do NOT use the following definition otherwise you won't be able to overwrite global variables
#
includes:
  # NOTE: How to use it. 
  # All the taskfiles under `tools/taskfiles/lib` are automatically downloaded from the `gsantoro/automation` repo
  # thanks to the taskfile `automation`. If those taskfiles are not there yet, follow these steps
  # 1. Comment out all the taskfiles with paths that start with `tools/taskfiles/lib`
  # 2. Run `task automation`
  # 3. Uncomment all the taskfiles with paths that start with `tools/taskfiles/lib`
  #
  # For this to work you need to have a .env.private with `GITHUB_TOKEN`.
  # This file is not under git since it contain secrets
  docker: tools/taskfiles/lib/docker.taskfile.yml
  devenv: tools/taskfiles/lib/devenv.taskfile.yml
  direnv: tools/taskfiles/lib/direnv.taskfile.yml
  poetry: tools/taskfiles/lib/poetry.taskfile.yml
  pulumi: tools/taskfiles/lib/pulumi.taskfile.yml
  
  # taskfiles ending in .yaml are only modified locally. They need to be pushed back to gsantoro/automation repo
  pulumi.gcp: tools/taskfiles/lib/pulumi.gcp.taskfile.yaml
  localstack: tools/taskfiles/lib/localstack.taskfile.yaml
  pulumi.aws: tools/taskfiles/lib/pulumi.aws.taskfile.yaml
  pulumi.localstack: tools/taskfiles/lib/pulumi.localstack.taskfile.yaml

  automation: tools/taskfiles/automation.taskfile.yml
  
